FROM ioglyph/todobackend-base:latest
MAINTAINER Benjamin Pack <ben.pack@gmail.com>

# Copy application artifacts
COPY target /wheelhouse

# Install application
RUN . /appenv/bin/activate && \
    pip install --no-index -f /wheelhouse todobackend && \
    rm -rf /wheelhouse

